from __future__ import annotations

import os
import sys


current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, "..", "..", ".."))
if project_root not in sys.path:
    sys.path.append(project_root)

from utils.variable_types import (  # noqa: E402
    VARIABLE_TYPE_BOOLEAN,
    VARIABLE_TYPE_BOOLEAN_COLUMN,
    VARIABLE_TYPE_COLUMN_NO_ERROR,
    VARIABLE_TYPE_COLUMN_WITH_ERROR_PER_VALUE,
    VARIABLE_TYPE_COLUMN_WITH_SINGLE_ERROR,
    VARIABLE_TYPE_COMPLEX,
    VARIABLE_TYPE_CONSTANT_NO_ERROR,
    VARIABLE_TYPE_CONSTANT_WITH_ERROR,
    VARIABLE_TYPE_FORMULA_NO_ERROR,
    VARIABLE_TYPE_FORMULA_WITH_ERROR,
    VARIABLE_TYPE_MATRIX,
    VARIABLE_TYPE_VECTOR,
)

__all__ = [
    "VARIABLE_TYPE_BOOLEAN",
    "VARIABLE_TYPE_BOOLEAN_COLUMN",
    "VARIABLE_TYPE_COLUMN_NO_ERROR",
    "VARIABLE_TYPE_COLUMN_WITH_ERROR_PER_VALUE",
    "VARIABLE_TYPE_COLUMN_WITH_SINGLE_ERROR",
    "VARIABLE_TYPE_COMPLEX",
    "VARIABLE_TYPE_CONSTANT_NO_ERROR",
    "VARIABLE_TYPE_CONSTANT_WITH_ERROR",
    "VARIABLE_TYPE_FORMULA_NO_ERROR",
    "VARIABLE_TYPE_FORMULA_WITH_ERROR",
    "VARIABLE_TYPE_MATRIX",
    "VARIABLE_TYPE_VECTOR",
]
